config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :showtimes do
    member do
      post 'book_ticket'
      delete 'cancel_ticket/:booking_id', action: :cancel_ticket, as: :cancel_ticket
    end
  end
  root 'showtimes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :showtime
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :showtimes, dependent: :destroy
end

app/models/showtime.rb
class Showtime < ApplicationRecord
  belongs_to :movie
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController
  def index
    @showtimes = Showtime.includes(:movie).all
  end

  def show
    @showtime = Showtime.find(params[:id])
    @available_seats = @showtime.available_seats
  end

  def book_ticket
    @showtime = Showtime.find(params[:id])
    if @showtime.available_seats > 0
      seat_number = @showtime.bookings.maximum(:seat_number).to_i + 1
      @showtime.bookings.create(seat_number: seat_number, user_name: params[:user_name])
      @showtime.update(available_seats: @showtime.available_seats - 1)
      flash[:success] = "Ticket booked successfully! Seat number: #{seat_number}"
    else
      flash[:error] = "Sorry, no seats available for this show."
    end
    redirect_to showtime_path(@showtime)
  end

  def cancel_ticket
    @booking = Booking.find(params[:booking_id])
    @showtime = @booking.showtime
    @booking.destroy
    @showtime.update(available_seats: @showtime.available_seats + 1)
    flash[:success] = "Ticket canceled successfully!"
    redirect_to showtime_path(@showtime)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookYourShow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/showtimes/index.html.erb
<h1>All Showtimes</h1>

<% @showtimes.each do |showtime| %>
  <div>
    <h2><%= showtime.movie.title %></h2>
    <p>Genre: <%= showtime.movie.genre %></p>
    <p>Show starts at: <%= showtime.start_time.to_datetime.strftime("%A, %d %B %Y %H:%M") %></p>
    <p>Show ends at: <%= showtime.end_time.to_datetime.strftime("%A, %d %B %Y %H:%M") %></p>
    <p>Available Seats: <%= showtime.available_seats %></p>
    <%= link_to "Book Ticket", showtime_path(showtime) %>
  </div>
  <hr>
<% end %>

app/views/showtimes/show.html.erb
<h1><%= @showtime.movie.title %></h1>
<p>Genre: <%= @showtime.movie.genre %></p>
<p>Show starts at: <%= @showtime.start_time.to_datetime.strftime("%A, %d %B %Y %H:%M") %></p>
<p>Show ends at: <%= @showtime.end_time.to_datetime.strftime("%A, %d %B %Y %H:%M") %></p>
<p>Available Seats: <%= @available_seats %></p>

<% if @showtime.available_seats > 0 %>
  <%= form_with(url: book_ticket_showtime_path(@showtime), method: :post) do |f| %>
    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
    </div>
    <%= f.submit "Book Ticket" %>
  <% end %>
<% else %>
  <p>Sorry, no seats available for this show.</p>
<% end %>

<% if @showtime.bookings.any? %>
  <h2>Booked Tickets</h2>
  <ul>
    <% @showtime.bookings.each do |booking| %>
      <li>
        Seat Number: <%= booking.seat_number %>
        | User Name: <%= booking.user_name %>
        | <%= link_to "Cancel", cancel_ticket_showtime_path(@showtime, booking), method: :delete, data: { confirm: "Are you sure you want to cancel this ticket?" } %>
      </li>
    <% end %>
  </ul>
<% end %>